import type { TrustedCompany } from "./types";

export const companies: TrustedCompany[] = [
  // =========================================================
  // GREENHOUSE
  // =========================================================
  {
    name: "Razorpay",
    slug: "razorpay",
    provider: "greenhouse",
    boardId: "razorpaysoftwareprivatelimited",
    enabled: true,
    trusted: true,
    logo: "https://razorpay.com/favicon.png",
    country: "India",
  },

  // =========================================================
  // INDIAN IT AND SERVICES COMPANIES
  // =========================================================
  {
    name: "Tata Consultancy Services",
    slug: "tcs",
    provider: "custom",
    careersUrl: "https://www.tcs.com/careers",
    parserId: "tcs",
    enabled: true,
    trusted: true,
    logo: "https://www.tcs.com/favicon.ico",
    country: "India",
  },
  {
    name: "Infosys",
    slug: "infosys",
    provider: "custom",
    careersUrl: "https://career.infosys.com/",
    parserId: "infosys",
    enabled: true,
    trusted: true,
    logo: "https://www.infosys.com/favicon.ico",
    country: "India",
  },
  {
    name: "Wipro",
    slug: "wipro",
    provider: "custom",
    careersUrl: "https://careers.wipro.com/",
    parserId: "wipro",
    enabled: true,
    trusted: true,
    logo: "https://www.wipro.com/favicon.ico",
    country: "India",
  },
  {
    name: "HCLTech",
    slug: "hcltech",
    provider: "custom",
    careersUrl: "https://www.hcltech.com/careers",
    parserId: "hcltech",
    enabled: true,
    trusted: true,
    logo: "https://www.hcltech.com/favicon.ico",
    country: "India",
  },
  {
    name: "Tech Mahindra",
    slug: "tech-mahindra",
    provider: "custom",
    careersUrl: "https://careers.techmahindra.com/",
    parserId: "tech-mahindra",
    enabled: true,
    trusted: true,
    logo: "https://www.techmahindra.com/favicon.ico",
    country: "India",
  },
  {
    name: "LTIMindtree",
    slug: "ltimindtree",
    provider: "custom",
    careersUrl: "https://www.ltimindtree.com/careers/",
    parserId: "ltimindtree",
    enabled: true,
    trusted: true,
    logo: "https://www.ltimindtree.com/favicon.ico",
    country: "India",
  },
  {
    name: "Mphasis",
    slug: "mphasis",
    provider: "custom",
    careersUrl: "https://careers.mphasis.com/",
    parserId: "mphasis",
    enabled: true,
    trusted: true,
    logo: "https://www.mphasis.com/favicon.ico",
    country: "India",
  },
  {
    name: "Persistent Systems",
    slug: "persistent",
    provider: "custom",
    careersUrl: "https://www.persistent.com/careers/",
    parserId: "persistent",
    enabled: true,
    trusted: true,
    logo: "https://www.persistent.com/favicon.ico",
    country: "India",
  },
  {
    name: "Coforge",
    slug: "coforge",
    provider: "custom",
    careersUrl: "https://careers.coforge.com/",
    parserId: "coforge",
    enabled: true,
    trusted: true,
    logo: "https://www.coforge.com/favicon.ico",
    country: "India",
  },
  {
    name: "Hexaware",
    slug: "hexaware",
    provider: "custom",
    careersUrl: "https://hexaware.com/careers/",
    parserId: "hexaware",
    enabled: true,
    trusted: true,
    logo: "https://hexaware.com/favicon.ico",
    country: "India",
  },

  // =========================================================
  // CONSULTING AND GLOBAL SERVICES
  // =========================================================
  {
    name: "Accenture",
    slug: "accenture",
    provider: "custom",
    careersUrl: "https://www.accenture.com/in-en/careers",
    parserId: "accenture",
    enabled: true,
    trusted: true,
    logo: "https://www.accenture.com/favicon.ico",
    country: "India",
  },
  {
    name: "IBM",
    slug: "ibm",
    provider: "custom",
    careersUrl: "https://www.ibm.com/careers",
    parserId: "ibm",
    enabled: true,
    trusted: true,
    logo: "https://www.ibm.com/favicon.ico",
    country: "India",
  },
  {
    name: "Cognizant",
    slug: "cognizant",
    provider: "custom",
    careersUrl: "https://careers.cognizant.com/",
    parserId: "cognizant",
    enabled: true,
    trusted: true,
    logo: "https://www.cognizant.com/favicon.ico",
    country: "India",
  },
  {
    name: "Capgemini",
    slug: "capgemini",
    provider: "custom",
    careersUrl: "https://www.capgemini.com/in-en/careers/",
    parserId: "capgemini",
    enabled: true,
    trusted: true,
    logo: "https://www.capgemini.com/favicon.ico",
    country: "India",
  },
  {
    name: "Deloitte",
    slug: "deloitte",
    provider: "custom",
    careersUrl: "https://www.deloitte.com/global/en/careers.html",
    parserId: "deloitte",
    enabled: true,
    trusted: true,
    logo: "https://www.deloitte.com/favicon.ico",
    country: "India",
  },
  {
    name: "EY",
    slug: "ey",
    provider: "custom",
    careersUrl: "https://careers.ey.com/",
    parserId: "ey",
    enabled: true,
    trusted: true,
    logo: "https://www.ey.com/favicon.ico",
    country: "India",
  },
  {
    name: "PwC",
    slug: "pwc",
    provider: "custom",
    careersUrl: "https://www.pwc.in/careers.html",
    parserId: "pwc",
    enabled: true,
    trusted: true,
    logo: "https://www.pwc.in/favicon.ico",
    country: "India",
  },
  {
    name: "KPMG",
    slug: "kpmg",
    provider: "custom",
    careersUrl: "https://kpmg.com/in/en/careers.html",
    parserId: "kpmg",
    enabled: true,
    trusted: true,
    logo: "https://kpmg.com/favicon.ico",
    country: "India",
  },
  {
    name: "Genpact",
    slug: "genpact",
    provider: "custom",
    careersUrl: "https://www.genpact.com/careers",
    parserId: "genpact",
    enabled: true,
    trusted: true,
    logo: "https://www.genpact.com/favicon.ico",
    country: "India",
  },
  {
    name: "DXC Technology",
    slug: "dxc-technology",
    provider: "custom",
    careersUrl: "https://careers.dxc.com/",
    parserId: "dxc",
    enabled: true,
    trusted: true,
    logo: "https://dxc.com/favicon.ico",
    country: "India",
  },
  {
    name: "NTT DATA",
    slug: "ntt-data",
    provider: "custom",
    careersUrl: "https://careers.nttdata.com/",
    parserId: "ntt-data",
    enabled: true,
    trusted: true,
    logo: "https://www.nttdata.com/favicon.ico",
    country: "India",
  },

  // =========================================================
  // GLOBAL PRODUCT AND TECHNOLOGY COMPANIES
  // =========================================================
  {
    name: "Google",
    slug: "google",
    provider: "custom",
    careersUrl: "https://www.google.com/about/careers/applications/jobs/results/",
    parserId: "google",
    enabled: true,
    trusted: true,
    logo: "https://www.google.com/favicon.ico",
    country: "India",
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    provider: "custom",
    careersUrl: "https://jobs.careers.microsoft.com/",
    parserId: "microsoft",
    enabled: true,
    trusted: true,
    logo: "https://www.microsoft.com/favicon.ico",
    country: "India",
  },
  {
    name: "Amazon",
    slug: "amazon",
    provider: "custom",
    careersUrl: "https://www.amazon.jobs/",
    parserId: "amazon",
    enabled: true,
    trusted: true,
    logo: "https://www.amazon.com/favicon.ico",
    country: "India",
  },
  {
    name: "Adobe",
    slug: "adobe",
    provider: "custom",
    careersUrl: "https://careers.adobe.com/",
    parserId: "adobe",
    enabled: true,
    trusted: true,
    logo: "https://www.adobe.com/favicon.ico",
    country: "India",
  },
  {
    name: "Oracle",
    slug: "oracle",
    provider: "oracle",
    careersUrl: "https://careers.oracle.com/",
    parserId: "oracle",
    enabled: true,
    trusted: true,
    logo: "https://www.oracle.com/favicon.ico",
    country: "India",
  },
  {
    name: "SAP",
    slug: "sap",
    provider: "successfactors",
    careersUrl: "https://jobs.sap.com/",
    parserId: "sap",
    enabled: true,
    trusted: true,
    logo: "https://www.sap.com/favicon.ico",
    country: "India",
  },
  {
    name: "Salesforce",
    slug: "salesforce",
    provider: "custom",
    careersUrl: "https://careers.salesforce.com/",
    parserId: "salesforce",
    enabled: true,
    trusted: true,
    logo: "https://www.salesforce.com/favicon.ico",
    country: "India",
  },
  {
    name: "Cisco",
    slug: "cisco",
    provider: "custom",
    careersUrl: "https://jobs.cisco.com/",
    parserId: "cisco",
    enabled: true,
    trusted: true,
    logo: "https://www.cisco.com/favicon.ico",
    country: "India",
  },
  {
    name: "Intel",
    slug: "intel",
    provider: "custom",
    careersUrl: "https://jobs.intel.com/",
    parserId: "intel",
    enabled: true,
    trusted: true,
    logo: "https://www.intel.com/favicon.ico",
    country: "India",
  },
  {
    name: "Qualcomm",
    slug: "qualcomm",
    provider: "custom",
    careersUrl: "https://careers.qualcomm.com/",
    parserId: "qualcomm",
    enabled: true,
    trusted: true,
    logo: "https://www.qualcomm.com/favicon.ico",
    country: "India",
  },
  {
    name: "Dell Technologies",
    slug: "dell",
    provider: "custom",
    careersUrl: "https://jobs.dell.com/",
    parserId: "dell",
    enabled: true,
    trusted: true,
    logo: "https://www.dell.com/favicon.ico",
    country: "India",
  },
  {
    name: "HP",
    slug: "hp",
    provider: "custom",
    careersUrl: "https://jobs.hp.com/",
    parserId: "hp",
    enabled: true,
    trusted: true,
    logo: "https://www.hp.com/favicon.ico",
    country: "India",
  },
  {
    name: "Siemens",
    slug: "siemens",
    provider: "custom",
    careersUrl: "https://jobs.siemens.com/",
    parserId: "siemens",
    enabled: true,
    trusted: true,
    logo: "https://www.siemens.com/favicon.ico",
    country: "India",
  },
  {
    name: "Bosch",
    slug: "bosch",
    provider: "custom",
    careersUrl: "https://www.bosch.in/careers/",
    parserId: "bosch",
    enabled: true,
    trusted: true,
    logo: "https://www.bosch.in/favicon.ico",
    country: "India",
  },
  {
    name: "Samsung",
    slug: "samsung",
    provider: "custom",
    careersUrl: "https://www.samsung.com/in/about-us/careers/",
    parserId: "samsung",
    enabled: true,
    trusted: true,
    logo: "https://www.samsung.com/favicon.ico",
    country: "India",
  },

  // =========================================================
  // BANKING AND FINANCIAL SERVICES
  // =========================================================
  {
    name: "JPMorgan Chase",
    slug: "jpmorgan-chase",
    provider: "custom",
    careersUrl: "https://careers.jpmorgan.com/",
    parserId: "jpmorgan",
    enabled: true,
    trusted: true,
    logo: "https://www.jpmorganchase.com/favicon.ico",
    country: "India",
  },
  {
    name: "Goldman Sachs",
    slug: "goldman-sachs",
    provider: "custom",
    careersUrl: "https://www.goldmansachs.com/careers/",
    parserId: "goldman-sachs",
    enabled: true,
    trusted: true,
    logo: "https://www.goldmansachs.com/favicon.ico",
    country: "India",
  },
  {
    name: "Morgan Stanley",
    slug: "morgan-stanley",
    provider: "custom",
    careersUrl: "https://www.morganstanley.com/people-opportunities",
    parserId: "morgan-stanley",
    enabled: true,
    trusted: true,
    logo: "https://www.morganstanley.com/favicon.ico",
    country: "India",
  },
  {
    name: "Wells Fargo",
    slug: "wells-fargo",
    provider: "custom",
    careersUrl: "https://www.wellsfargojobs.com/",
    parserId: "wells-fargo",
    enabled: true,
    trusted: true,
    logo: "https://www.wellsfargo.com/favicon.ico",
    country: "India",
  },
  {
    name: "HSBC",
    slug: "hsbc",
    provider: "custom",
    careersUrl: "https://www.hsbc.com/careers",
    parserId: "hsbc",
    enabled: true,
    trusted: true,
    logo: "https://www.hsbc.com/favicon.ico",
    country: "India",
  },
  {
    name: "Barclays",
    slug: "barclays",
    provider: "custom",
    careersUrl: "https://search.jobs.barclays/",
    parserId: "barclays",
    enabled: true,
    trusted: true,
    logo: "https://www.barclays.com/favicon.ico",
    country: "India",
  },
  {
    name: "Deutsche Bank",
    slug: "deutsche-bank",
    provider: "custom",
    careersUrl: "https://careers.db.com/",
    parserId: "deutsche-bank",
    enabled: true,
    trusted: true,
    logo: "https://www.db.com/favicon.ico",
    country: "India",
  },
  {
    name: "Citi",
    slug: "citi",
    provider: "custom",
    careersUrl: "https://jobs.citi.com/",
    parserId: "citi",
    enabled: true,
    trusted: true,
    logo: "https://www.citi.com/favicon.ico",
    country: "India",
  },
  {
    name: "American Express",
    slug: "american-express",
    provider: "custom",
    careersUrl: "https://www.americanexpress.com/en-us/careers/",
    parserId: "american-express",
    enabled: true,
    trusted: true,
    logo: "https://www.americanexpress.com/favicon.ico",
    country: "India",
  },
  {
    name: "Mastercard",
    slug: "mastercard",
    provider: "custom",
    careersUrl: "https://careers.mastercard.com/",
    parserId: "mastercard",
    enabled: true,
    trusted: true,
    logo: "https://www.mastercard.com/favicon.ico",
    country: "India",
  },
  {
    name: "Visa",
    slug: "visa",
    provider: "custom",
    careersUrl: "https://corporate.visa.com/en/careers.html",
    parserId: "visa",
    enabled: true,
    trusted: true,
    logo: "https://www.visa.com/favicon.ico",
    country: "India",
  },

  // =========================================================
  // INDIAN PRODUCT AND INTERNET COMPANIES
  // =========================================================
  {
    name: "Flipkart",
    slug: "flipkart",
    provider: "custom",
    careersUrl: "https://www.flipkartcareers.com/",
    parserId: "flipkart",
    enabled: true,
    trusted: true,
    logo: "https://www.flipkart.com/favicon.ico",
    country: "India",
  },
  {
    name: "PhonePe",
    slug: "phonepe",
    provider: "custom",
    careersUrl: "https://www.phonepe.com/careers/",
    parserId: "phonepe",
    enabled: true,
    trusted: true,
    logo: "https://www.phonepe.com/favicon.ico",
    country: "India",
  },
  {
    name: "Meesho",
    slug: "meesho",
    provider: "custom",
    careersUrl: "https://www.meesho.io/jobs",
    parserId: "meesho",
    enabled: true,
    trusted: true,
    logo: "https://www.meesho.com/favicon.ico",
    country: "India",
  },
  {
    name: "Swiggy",
    slug: "swiggy",
    provider: "custom",
    careersUrl: "https://careers.swiggy.com/",
    parserId: "swiggy",
    enabled: true,
    trusted: true,
    logo: "https://www.swiggy.com/favicon.ico",
    country: "India",
  },
  {
    name: "Zomato",
    slug: "zomato",
    provider: "custom",
    careersUrl: "https://www.zomato.com/careers",
    parserId: "zomato",
    enabled: true,
    trusted: true,
    logo: "https://www.zomato.com/favicon.ico",
    country: "India",
  },
  {
    name: "Paytm",
    slug: "paytm",
    provider: "custom",
    careersUrl: "https://paytm.com/careers/",
    parserId: "paytm",
    enabled: true,
    trusted: true,
    logo: "https://paytm.com/favicon.ico",
    country: "India",
  },
  {
    name: "Freshworks",
    slug: "freshworks",
    provider: "custom",
    careersUrl: "https://www.freshworks.com/company/careers/",
    parserId: "freshworks",
    enabled: true,
    trusted: true,
    logo: "https://www.freshworks.com/favicon.ico",
    country: "India",
  },
  {
    name: "Zoho",
    slug: "zoho",
    provider: "custom",
    careersUrl: "https://www.zoho.com/careers/",
    parserId: "zoho",
    enabled: true,
    trusted: true,
    logo: "https://www.zoho.com/favicon.ico",
    country: "India",
  },
  {
    name: "BrowserStack",
    slug: "browserstack",
    provider: "custom",
    careersUrl: "https://www.browserstack.com/careers",
    parserId: "browserstack",
    enabled: true,
    trusted: true,
    logo: "https://www.browserstack.com/favicon.ico",
    country: "India",
  },
];

export function getEnabledTrustedCompanies(): TrustedCompany[] {
  return companies.filter(
    (company) => company.enabled && company.trusted
  );
}

export function getCompanyBySlug(
  slug: string
): TrustedCompany | undefined {
  const normalizedSlug = slug.trim().toLowerCase();

  return companies.find(
    (company) => company.slug.toLowerCase() === normalizedSlug
  );
}

export function getCompaniesByProvider(
  provider: TrustedCompany["provider"]
): TrustedCompany[] {
  return companies.filter(
    (company) =>
      company.provider === provider &&
      company.enabled &&
      company.trusted
  );
}